version: '2'

services:
  templateapi:
    image: kickster/coreapi-template
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=kickster
      - SPRING_DATASOURCE_PASSWORD=kickster123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://templatemysql/kickster_db_template'
    links:
      - discovery
      - templatemysql
  templatemysql:
    image: kickster/datastore-template
    volumes:
      - /data
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=kickster_db_template
      - MYSQL_USER=kickster
      - MYSQL_PASSWORD=kickster123
      - MYSQL_ROOT_PASSWORD=kickster123
  artifactapi:
    image: kickster/coreapi-artifact
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=kickster
      - SPRING_DATASOURCE_PASSWORD=kickster123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://artifactmysql:3306/kickster_db_artifact'
    links:
      - discovery
  gateway:
    image: kickster/api-gateway
    ports:
      - 80:8765
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - discovery
  discovery:
    image: kickster/discovery-service
    ports:
      - 8761:8761
