version: '2'

services:
  memberapi:
    image: kickster/coreapi-member
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=kickster
      - SPRING_DATASOURCE_PASSWORD=kickster123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://membermysql:3306/kickster_db_member'
    links:
      - discovery
      - membermysql
  membermysql:
    image: kickster/datastore-member
    volumes:
      - /data
    environment:
      - MYSQL_DATABASE=kickster_db_member
      - MYSQL_USER=kickster
      - MYSQL_PASSWORD=kickster123
      - MYSQL_ROOT_PASSWORD=kickster123
  contentapi:
    image: kickster/coreapi-content
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=kickster
      - SPRING_DATASOURCE_PASSWORD=kickster123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://contentmysql:3306/kickster_db_content'
    links:
      - discovery
      - contentmysql
  contentmysql:
    image: kickster/datastore-content
    volumes:
      - /data
    environment:
      - MYSQL_DATABASE=kickster_db_content
      - MYSQL_USER=kickster
      - MYSQL_PASSWORD=kickster123
      - MYSQL_ROOT_PASSWORD=kickster123
  modelapi:
    image: kickster/coreapi-model
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=kickster
      - SPRING_DATASOURCE_PASSWORD=kickster123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://modelmysql/kickster_db_model'
      - 'SPRING_DATA_MONGODB_URI=mongodb://schemamongo:27017/kickster_db_schema'
    links:
      - discovery
      - modelmysql
      - schemamongo
  modelmysql:
    image: kickster/datastore-model
    volumes:
      - /data
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=kickster_db_model
      - MYSQL_USER=kickster
      - MYSQL_PASSWORD=kickster123
      - MYSQL_ROOT_PASSWORD=kickster123
  templateapi:
    image: kickster/coreapi-template
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=kickster
      - SPRING_DATASOURCE_PASSWORD=kickster123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://templatemysql/kickster_db_template'
    links:
      - discovery
      - templatemysql
  templatemysql:
    image: kickster/datastore-template
    volumes:
      - /data
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=kickster_db_template
      - MYSQL_USER=kickster
      - MYSQL_PASSWORD=kickster123
      - MYSQL_ROOT_PASSWORD=kickster123
  gateway:
    image: kickster/api-gateway
    ports:
      - 80:8765
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - discovery
  discovery:
    image: kickster/discovery-service
    ports:
      - 8761:8761
  artifactapi:
    image: kickster/coreapi-artifact
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=kickster
      - SPRING_DATASOURCE_PASSWORD=kickster123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://artifactmysql:3306/kickster_db_artifact'
      - SPRING_RABBITMQ_HOST=eventstore
      - SPRING_RABBITMQ_USERNAME=kickster
      - SPRING_RABBITMQ_PASSWORD=kickster123
    links:
      - discovery
      - eventstore
      - artifactmysql
  artifactmysql:
    image: kickster/datastore-artifact
    volumes:
      - /data
    environment:
      - MYSQL_DATABASE=kickster_db_artifact
      - MYSQL_USER=kickster
      - MYSQL_PASSWORD=kickster123
      - MYSQL_ROOT_PASSWORD=kickster123
  eventstore:
    image: tutum/rabbitmq
    environment:
      - RABBITMQ_USER=kickster
      - RABBITMQ_PASS=kickster123
    ports:
      - "15672:15672"
      - "5672:5672"
  schemamongo:
    image: kickster/datastore-schema
    ports:
      - "27017:27017"
    volumes:
      - /data
  bootifulcodegen:
    image: kickster/codegen-bootiful
    links:
      - eventstore
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=eventstore
      - SPRING_RABBITMQ_USERNAME=kickster
      - SPRING_RABBITMQ_PASSWORD=kickster123
  gonutscodegen:
    image: kickster/codegen-gonuts
    links:
      - eventstore
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=eventstore
      - SPRING_RABBITMQ_USERNAME=kickster
      - SPRING_RABBITMQ_PASSWORD=kickster123
  nodeexpressjscodegen:
    image: kickster/codegen-nodeexpressjs
    links:
      - eventstore
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=eventstore
      - SPRING_RABBITMQ_USERNAME=kickster
      - SPRING_RABBITMQ_PASSWORD=kickster123
  pythonflaskcodegen:
    image: kickster/codegen-pythonflask
    links:
      - eventstore
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=eventstore
      - SPRING_RABBITMQ_USERNAME=kickster
      - SPRING_RABBITMQ_PASSWORD=kickster123
