version: '3'

services:
  microserviceapi:
    image: rockstarproject/coreapi-microservice
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - "SPRING_DATA_MONGODB_URI=mongodb://microservicemongo:27017/rockstar_db_microservice"
    depends_on:
      - discovery
      - microservicemongo
  microservicemongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - microservice-data:/data/db
  productapi:
    image: rockstarproject/coreapi-product
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
      - SPRING_DATASOURCE_USERNAME=rockstar
      - SPRING_DATASOURCE_PASSWORD=rockstar123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://productmysql/rockstar_db_product'
    depends_on:
      - discovery
      - productmysql
  productmysql:
    image: rockstarproject/datastore-product
    volumes:
      - product-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=rockstar_db_product
      - MYSQL_USER=rockstar
      - MYSQL_PASSWORD=rockstar123
      - MYSQL_ROOT_PASSWORD=rockstar123
  collectionapi:
    image: rockstarproject/coreapi-collection
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
      - SPRING_DATASOURCE_USERNAME=rockstar
      - SPRING_DATASOURCE_PASSWORD=rockstar123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://collectionmysql/rockstar_db_collection'
      - MANAGEMENT_SECURITY_ENABLED=false
    depends_on:
      - discovery
      - collectionmysql
  collectionmysql:
    image: rockstarproject/datastore-collection
    volumes:
      - collection-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=rockstar_db_collection
      - MYSQL_USER=rockstar
      - MYSQL_PASSWORD=rockstar123
      - MYSQL_ROOT_PASSWORD=rockstar123
  artifactapi:
    image: rockstarproject/coreapi-artifact
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
    depends_on:
      - discovery
  gateway:
    image: rockstarproject/api-gateway
    ports:
      - 80:8765
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery
  discovery:
    image: rockstarproject/discovery-service
    ports:
      - 8761:8761
  
volumes:
  product-data:
  collection-data:
  microservice-data:
