version: '3'

services:
  metadataapi:
    image: rockstarproject/coreapi-metadata
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
      - "SPRING_DATA_MONGODB_URI=mongodb://metadatamongo:27017/rockstar_db_metadata"
    depends_on:
      - discovery
      - metadatamongo
  metadataseed:
    image: rockstarproject/datastore-metadata
    depends_on:
      - metadatamongo
    command:
      "mongoimport --host metadatamongo --db rockstar_db_metadata --collection metadata --type json --file metadata.json --jsonArray"
  metadatamongo:
    image: rockstarproject/datastore-metadata
    ports:
      - "27017:27017"
    volumes:
      - metadata-data:/data/db
  productapi:
    image: rockstarproject/coreapi-product
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
      - SPRING_DATASOURCE_USERNAME=rockstar
      - SPRING_DATASOURCE_PASSWORD=rockstar123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://productmysql/rockstar_db_product'
    depends_on:
      - discovery
      - productmysql
  productmysql:
    image: rockstarproject/datastore-product
    volumes:
      - product-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=rockstar_db_product
      - MYSQL_USER=rockstar
      - MYSQL_PASSWORD=rockstar123
      - MYSQL_ROOT_PASSWORD=rockstar123
  collectionapi:
    image: rockstarproject/coreapi-collection
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
      - SPRING_DATASOURCE_USERNAME=rockstar
      - SPRING_DATASOURCE_PASSWORD=rockstar123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://collectionmysql/rockstar_db_collection'
    depends_on:
      - discovery
      - collectionmysql
  collectionmysql:
    image: rockstarproject/datastore-collection
    volumes:
      - collection-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=rockstar_db_collection
      - MYSQL_USER=rockstar
      - MYSQL_PASSWORD=rockstar123
      - MYSQL_ROOT_PASSWORD=rockstar123
  artifactapi:
    image: rockstarproject/coreapi-artifact
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
    depends_on:
      - discovery
  gateway:
    image: rockstarproject/api-gateway
    ports:
      - 80:8765
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery
  discovery:
    image: rockstarproject/discovery-service
    ports:
      - 8761:8761

volumes:
  metadata-data:
  product-data:
  collection-data:
