version: '3'

services:
  metadataapi:
    image: rockstarproject/coreapi-metadata
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
      - "SPRING_DATA_MONGODB_URI=mongodb://metadatamongo:27017/rockstar_db_metadata"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  metadataseed:
    image: rockstarproject/datastore-metadata
    command:
      "mongoimport --host metadatamongo --db rockstar_db_metadata --collection metadata --type json --file metadata.json --jsonArray"
    deploy:
      placement:
        constraints: [node.role == worker]
  metadatamongo:
    image: rockstarproject/datastore-metadata
    ports:
      - "27017:27017"
    volumes:
      - /data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  productapi:
    image: rockstarproject/coreapi-product
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
      - SPRING_DATASOURCE_USERNAME=rockstar
      - SPRING_DATASOURCE_PASSWORD=rockstar123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://productmysql/rockstar_db_product'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  productmysql:
    image: rockstarproject/datastore-product
    volumes:
      - /data
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=rockstar_db_product
      - MYSQL_USER=rockstar
      - MYSQL_PASSWORD=rockstar123
      - MYSQL_ROOT_PASSWORD=rockstar123
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  collectionapi:
    image: rockstarproject/coreapi-collection
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
      - SPRING_DATASOURCE_USERNAME=rockstar
      - SPRING_DATASOURCE_PASSWORD=rockstar123
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://collectionmysql/rockstar_db_collection'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  collectionmysql:
    image: rockstarproject/datastore-collection
    volumes:
      - /data
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=rockstar_db_collection
      - MYSQL_USER=rockstar
      - MYSQL_PASSWORD=rockstar123
      - MYSQL_ROOT_PASSWORD=rockstar123
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  artifactapi:
    image: rockstarproject/coreapi-artifact
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_ISSUER=https://rockstar.auth0.com/
      - AUTH0_AUDIENCE=https://api.rock-star.io/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  gateway:
    image: rockstarproject/api-gateway
    ports:
      - 80:8765
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  discovery:
    image: rockstarproject/discovery-service
    ports:
      - 8761:8761
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
