artifactapi:
  environment:
    - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=https://prepiam.toronto.ca.ibm.com/idaas/oidc/endpoint/default/userinfo'
    - SPRING_PROFILES_ACTIVE=docker
  image: $DOCKER_REGISTRY/kickster/coreapi-artifact:latest
  links:
    - discovery
contentapi:
  environment:
    - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=https://prepiam.toronto.ca.ibm.com/idaas/oidc/endpoint/default/userinfo'
    - SPRING_DATASOURCE_PASSWORD=kickster123
    - 'SPRING_DATASOURCE_URL=jdbc:mysql://contentmysql:3306/kickster_db_content'
    - SPRING_DATASOURCE_USERNAME=kickster
    - SPRING_PROFILES_ACTIVE=docker
  image: $DOCKER_REGISTRY/kickster/coreapi-content:latest
  links:
    - contentmysql
    - discovery
contentmysql:
  environment:
    - MYSQL_DATABASE=kickster_db_content
    - MYSQL_PASSWORD=kickster123
    - MYSQL_ROOT_PASSWORD=kickster123
    - MYSQL_USER=kickster
  image: $DOCKER_REGISTRY/kickster/datastore-content:latest
discovery:
  image: $DOCKER_REGISTRY/kickster/sharedservice-discovery:latest
  ports:
    - '8761:8761'
gateway:
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  image: $DOCKER_REGISTRY/kickster/api-gateway:latest
  links:
    - discovery
  ports:
    - '80:8765'
modelapi:
  environment:
    - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=https://prepiam.toronto.ca.ibm.com/idaas/oidc/endpoint/default/userinfo'
    - SPRING_DATASOURCE_PASSWORD=kickster123
    - 'SPRING_DATASOURCE_URL=jdbc:mysql://modelmysql:3306/kickster_db_model'
    - SPRING_DATASOURCE_USERNAME=kickster
    - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    - SPRING_JPA_SHOW_SQL=true
    - SPRING_PROFILES_ACTIVE=docker
  image: $DOCKER_REGISTRY/kickster/coreapi-model:latest
  links:
    - discovery
    - modelmysql
modelmysql:
  environment:
    - MYSQL_DATABASE=kickster_db_model
    - MYSQL_PASSWORD=kickster123
    - MYSQL_ROOT_PASSWORD=kickster123
    - MYSQL_USER=kickster
  image: $DOCKER_REGISTRY/kickster/datastore-model:latest
templateapi:
  environment:
    - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=https://prepiam.toronto.ca.ibm.com/idaas/oidc/endpoint/default/userinfo'
    - SPRING_DATASOURCE_PASSWORD=kickster123
    - 'SPRING_DATASOURCE_URL=jdbc:mysql://templatemysql:3306/kickster_db_template'
    - SPRING_DATASOURCE_USERNAME=kickster
    - SPRING_PROFILES_ACTIVE=docker
  image: $DOCKER_REGISTRY/kickster/coreapi-template:latest
  links:
    - discovery
    - templatemysql
  restart: always
templatemysql:
  environment:
    - MYSQL_DATABASE=kickster_db_template
    - MYSQL_PASSWORD=kickster123
    - MYSQL_ROOT_PASSWORD=kickster123
    - MYSQL_USER=kickster
  image: $DOCKER_REGISTRY/kickster/datastore-template:latest
